### ISSUE TITLE
методы Storage и возня с sql

### ISSUE THREAD

**Issue by mishhgun01** [bazalt-technologies/retelling#3]
Необходимо создать отдельную таблицу жанров, тем самым разделить логику работы БД в пакете SQL. Поддержать это на следующем уровне в методах Storage, а также сделать INSERT-ы основных жанров искусства и типов.
Плюс написать новые методы для Storage UpdateReview и DeleteReview.

Появилась такая мысля - у отдального типа творчества могут быть разные жанры - т.е. у книги нет жанра "слэшер" или "трэш".
Думаю, стоит связать таблицу жанров с таблицей типов и также поддержать это в методах.

**Comment by GarlicRoll** [comment]
По Update
	// Возможно стоит учитывать то, что будут обновляться только некоторые поля
	// Для этого можно сделать по методу на каждое поле, либо как-то вводить data с пустыми полями,
	// Чтобы можно было определить, что их трогать не надо
По изменению методов для новых genres
      Создавать ли новые структуры в models?
      Или в программе у нас будут не ссылки, а сразу данные?
      Я бы сделал аналогчино как в бд на SQL, те сделал бы новые структуры
